### ISSUE TITLE
Find/create a sexual harassment dataset

### ISSUE THREAD

**Issue by malteserteresa** [opt-out-tool/opt-out#3]

**Comment by jancborchardt** [comment]
@malteserteresa Maybe it’s good to link up with Caroline Sinders here (if you haven’t already). She works on ["An Incomplete (but growing) History of Harassment Campaigns since 2003"](https://medium.com/digitalhks/an-incomplete-but-growing-history-of-harassment-campaigns-since-2003-db0649522fa8).

Related tweet here: https://twitter.com/carolinesinders/status/1066981552284930050

**Comment by MikeJohnPage** [comment]
I am on this issue. See 'Creating a Data Set' Wiki.

**Comment by MikeJohnPage** [comment]
In addition to finding a source of data, a definition of 'sexual harassment and sexist hate speech' in keeping with the academic literature is required. As it currently stands, the literature has a plethora of definitions and concepts surrounding harassment and hate crime, etc.

There is a real risk of either: (i) taking too narrow of an approach and excluding genuinely dangerous and harmful comments at the expense of trying to fit in a perfect theoretical framework, or (ii) taking such a broad brush approach that the app both loses its specificity to blocking 'sexual harassment and sexist hate speech' and becomes overly-sensitive, rendering it a poor user experience.

**Comment by MikeJohnPage** [comment]
Cont.

As part of the data set generation, there will invariably be a manual labelling step (using a tool like [prodigy](https://prodi.gy/) or [LightTag](https://www.lighttag.io/) to classify the training data as sexually harassing/non-harassing (should a binary classifier be chosen). A strict schema needs to be generated to guide those labelling tweets. This will prove to be the largest source of subjective bias and subsequently will have a large effect on the final model.
